# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np
arr = np.array(my_list)

In [3]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2) #(start, end, step)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(4) 

array([0., 0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((1,2))

array([[1., 1.]])

In [16]:
np.linspace(0,5,5) #(start,stop,evenly spaced step)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [17]:
# for identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#Random Numbers
np.random.rand(5) #random number between 0 and 1

array([0.55824756, 0.45709668, 0.35538402, 0.84553558, 0.11115289])

In [20]:
np.random.rand(5,5)

array([[0.80469974, 0.67912764, 0.45537448, 0.83774023, 0.04801372],
       [0.43787777, 0.1706253 , 0.96234275, 0.56431678, 0.73401744],
       [0.49781712, 0.88619732, 0.42916312, 0.1243897 , 0.50257589],
       [0.19172794, 0.23118255, 0.58985839, 0.59587424, 0.95677118],
       [0.24871267, 0.06894914, 0.48649514, 0.43285574, 0.99049428]])

In [21]:
np.random.randn(2) #standard normal distribution center around zero

array([-1.40115752,  0.70192018])

In [22]:
np.random.rand(3,3)

array([[0.21212549, 0.03815618, 0.23018093],
       [0.05238282, 0.2884509 , 0.77242664],
       [0.29291389, 0.10885731, 0.01710124]])

In [27]:
#Random integer
np.random.randint(1,100,10)

array([ 7,  4,  8, 47, 43, 90, 68, 57, 43, 68])

In [29]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)
ranarr

array([39, 27, 18, 14, 11, 18, 34, 20,  3, 17])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.max() #Maximum value

39

In [37]:
ranarr.argmax() #index of maxvalue

0

In [35]:
ranarr.min() #Minimum value

3

In [38]:
ranarr.argmin()

8

In [36]:
ranarr.mean()

20.1

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr.shape

(5, 5)

In [46]:
arr.dtype

dtype('int64')